### ISSUE TITLE
Can't set initial index parameter

### ISSUE THREAD

**Issue by AbhijeetMallick** [hyperoslo/Dropdowns#9]
I am setting up Dropdowns in my project using cocoapods. But I can't see the initial index parameter to 'TitleView'. I guess it was added recently.
![screen shot 2017-12-26 at 2 42 11 pm](https://user-images.githubusercontent.com/18901576/34352867-05171956-ea4b-11e7-9e77-facbb8689f3c.png)

**Comment by onmyway133** [comment]
@AbhijeetMallick Hi, you're right. It was added in this PR https://github.com/hyperoslo/Dropdowns/pull/7 In the mean time you can fetch from master because no new releases were made yet

**Comment by AbhijeetMallick** [comment]
Thanks @onmyway133

**Comment by onmyway133** [comment]
@AbhijeetMallick Nice. I will close this issue for now
